name: Screenify Backend staging

on:
  push:
    branches: ['test']

jobs:
  Server:
    name: 'Staging Server'
    runs-on: [test]

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          clean: 'false'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm i
      - name: Build Project
        run: CI=false npm run build --if-present
      - name: Run migrations
        run: npm run db:testMigrate --if-present
      - name: Restart server
        run: npm run pm2TestRestartRun --if-present
